--USE DATABASE VT_SARF_MAZLEME;

--1
Create table TEDARIKCI(
T_ID int primary key,
AD varchar(40),
VERGI_NO int not null,
TEDARIK_EDILEN_URUN_KODU int,
ADRES varchar(60) default 'KONYA'
);

--2
alter table MUSTERI alter column MUSTERI_NO int not null
alter table MUSTERI add constraint PK_MUSTERI primary key (MUSTERI_NO)
alter table SIPARIS add constraint FK_MUSTERI foreign key (MUSTERI_KODU) references MUSTERI (MUSTERI_NO) on delete set null

--3
alter table URUN alter column U_ID int not null
alter table URUN add constraint PK_Urun primary key (U_ID)
alter table TEDARIKCI add constraint FK_Urun foreign key (TEDARIK_EDILEN_URUN_KODU) references URUN (U_ID) on delete cascade

--4
select sum(URUN.BIRIM_FIYAT*SIPARIS.MIKTAR) as TOPLAM_TUTAR from URUN inner join SIPARIS ON SIPARIS.URUN_KODU = URUN.U_ID

--5
select MUSTERI.AD, MUSTERI.SOYAD, MUSTERI.TELEFON, sum(URUN.BIRIM_FIYAT*SIPARIS.MIKTAR) as TOPLAM_TUTAR from
((MUSTERI inner join SIPARIS ON MUSTERI.MUSTERI_NO = SIPARIS.MUSTERI_KODU and MUSTERI.AD = 'Ayþe') inner join URUN ON SIPARIS.URUN_KODU = URUN.U_ID) 
group by MUSTERI.AD, MUSTERI.SOYAD, MUSTERI.TELEFON

--6
CREATE VIEW SIPARIS_BILGILERI
as select MUSTERI.AD as MUSTERI_ADI, MUSTERI.SOYAD, URUN.AD, URUN.BIRIM_FIYAT, SIPARIS.MIKTAR, URUN.BIRIM_FIYAT*SIPARIS.MIKTAR as FIYAT_TUTARI from 
((MUSTERI inner join SIPARIS on MUSTERI.MUSTERI_NO=SIPARIS.MUSTERI_KODU) inner join URUN on SIPARIS.URUN_KODU = URUN.U_ID)

--7
Select SIPARIS.ODEME_TURU, sum(SIPARIS.MIKTAR*URUN.BIRIM_FIYAT) as TOPLAM_TUTAR from 
URUN inner join SIPARIS on SIPARIS.URUN_KODU = URUN.U_ID group by SIPARIS.ODEME_TURU

--8
CREATE VIEW [LISTE_CASE] AS SELECT MUSTERI.MUSTERI_NO, MUSTERI.AD + ' '+ MUSTERI.SOYAD as AD_SOYAD,
	CASE SIPARIS.ODEME_TURU
	    WHEN 1 THEN SIPARIS.MIKTAR*URUN.BIRIM_FIYAT
		ELSE NULL
    END [PESIN],
	
	CASE SIPARIS.ODEME_TURU
	    WHEN 2 THEN SIPARIS.MIKTAR*URUN.BIRIM_FIYAT
        ELSE NULL
    END [KREDI],
	
	CASE SIPARIS.ODEME_TURU
	    WHEN 3 THEN SIPARIS.MIKTAR*URUN.BIRIM_FIYAT
        ELSE NULL
    END [CEK]

FROM SIPARIS
INNER JOIN MUSTERI ON SIPARIS.MUSTERI_KODU=MUSTERI.MUSTERI_NO
INNER JOIN URUN ON URUN.U_ID=SIPARIS.URUN_KODU;

SELECT LISTE_CASE.MUSTERI_NO, LISTE_CASE.AD_SOYAD, SUM(LISTE_CASE.PESIN) [PESIN], SUM(LISTE_CASE.KREDI) [KREDI], SUM(LISTE_CASE.CEK) [CEK] FROM LISTE_CASE
GROUP BY LISTE_CASE.MUSTERI_NO, LISTE_CASE.AD_SOYAD ORDER BY LISTE_CASE.MUSTERI_NO;