USE VTDERS21EKIM

SELECT ISIM, SOYISIM, YAS FROM PERSONEL WHERE YAS IN((SELECT MAX(YAS) FROM PERSONEL), (SELECT MIN(YAS) FROM PERSONEL))

SELECT ULKE, AVG(MAAS) AS ORTALAMA_MAAS FROM PERSONEL GROUP BY ULKE
--PERSONELLERÝ ÜLKELERE GÖRE GRUPLAYAN VE GRUPLARIN MAAÞ ORTALAMALARINI VE ÜLKELERÝ GÖSTERME


SELECT ULKE, AVG(YAS) AS ORT_YAS, AVG(MAAS) AS ORT_MAAS, COUNT(*) AS PER_SAYI FROM PERSONEL WHERE MAAS>=2000 GROUP BY ULKE HAVING AVG(YAS)>=25

--YOL 1(SIKINTILI)
SELECT MAAS.ULKE, MAX(ORT_MAAS) AS ORT_MAAS FROM (SELECT ULKE, AVG(MAAS) AS ORT_MAAS FROM PERSONEL GROUP BY ULKE) AS MAAS
--YOL 2 
SELECT KENT, AVG(MAAS) AS ORT_MAAS FROM PERSONEL GROUP BY KENT ORDER BY AVG(MAAS) DESC

SELECT ISIM, MAAS from PERSONEL where MAAS < (SELECT AVG(MAAS) as ORT_MAAS from PERSONEL) 

DELETE PERSONEL where PER_NO = 8 and ISIM = 'x'

INSERT INTO PERSONEL(PER_NO, ISIM, SOYISIM, KENT, CINSIYET) VALUES(11, 'x', 'y', 'Paris','E')

SELECT * FROM PERSONEL

ALTER TABLE PERSONEL DROP COLUMN MAAS

DROP TABLE PERSONEL

